-- MySQL Script generated by MySQL Workbench
-- 10/20/16 08:59:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sams
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sams
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sams` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `sams` ;

-- -----------------------------------------------------
-- Table `sams`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sams`.`course` (
  `course_id` CHAR(10) NOT NULL,
  `course_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`course_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sams`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sams`.`teacher` (
  `tea_id` CHAR(10) NOT NULL,
  `tea_name` VARCHAR(20) NOT NULL,
  `tea_password` VARCHAR(255) NOT NULL,
  `tea_dep` VARCHAR(20) NOT NULL,
  `tea_active` CHAR(1) NOT NULL,
  `tea_lock` CHAR(1) NOT NULL,
  PRIMARY KEY (`tea_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sams`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sams`.`project` (
  `pro_id` INT NOT NULL AUTO_INCREMENT,
  `year` CHAR(4) NOT NULL,
  `term` CHAR(1) NOT NULL,
  `course_id` CHAR(10) NOT NULL,
  `course_name` VARCHAR(20) NOT NULL,
  `stu_grade` CHAR(4) NOT NULL,
  `stu_major` VARCHAR(20) NOT NULL,
  `tea_id` CHAR(10) NOT NULL,
  `tea_name` VARCHAR(20) NOT NULL,
  `hour` CHAR(3) NOT NULL,
  `last_update` CHAR(20) NOT NULL,
  `status` CHAR(3) NOT NULL,
  `off_time` CHAR(20) NOT NULL,
  PRIMARY KEY (`pro_id`),
  UNIQUE INDEX `pro_unique` (`year` ASC, `term` ASC, `course_id` ASC, `stu_grade` ASC, `stu_major` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sams`.`attend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sams`.`attend` (
  `at_id` INT NOT NULL AUTO_INCREMENT,
  `pro_id` VARCHAR(45) NOT NULL,
  `stu_id` CHAR(10) NOT NULL,
  `no_sum` INT NOT NULL,
  PRIMARY KEY (`at_id`),
  UNIQUE INDEX `at_unique` (`pro_id` ASC, `stu_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sams`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sams`.`student` (
  `stu_id` CHAR(10) NOT NULL,
  `stu_name` VARCHAR(20) NOT NULL,
  `stu_sex` CHAR(1) NOT NULL,
  `stu_grade` CHAR(4) NOT NULL,
  `stu_dep` VARCHAR(20) NOT NULL,
  `stu_major` VARCHAR(20) NOT NULL,
  `stu_class` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`stu_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sams`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sams`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `user_password_hash` VARCHAR(255) NOT NULL,
  `user_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sams`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sams`.`log` (
  `log_id` INT NOT NULL AUTO_INCREMENT,
  `log_time` CHAR(20) NULL,
  `user_name` VARCHAR(64) NULL,
  `action` TEXT NULL,
  `ipa` VARCHAR(45) NULL,
  `ipb` VARCHAR(45) NULL,
  `user_agent` TEXT NULL,
  PRIMARY KEY (`log_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
